apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cpu-workloads
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
    budgets:
    - nodes: "10%"
  template:
    metadata:
      labels:
        workload: cpu
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-nodes
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c7i.2xlarge
        - c7i.4xlarge
